"use client"

interface Props {
  targetExam?: string
}

export function StudyPlanPlaceholder({ targetExam }: Props) {
  return (
    <div className="bg-white/[0.03] border border-white/[0.07] rounded-2xl p-5 relative overflow-hidden">
      {/* Decorative background pattern */}
      <div
        className="absolute inset-0 opacity-[0.03]"
        style={{
          backgroundImage: `repeating-linear-gradient(
            45deg,
            #e8d5a3 0px,
            #e8d5a3 1px,
            transparent 1px,
            transparent 12px
          )`,
        }}
      />

      <div className="relative">
        <div className="flex items-center justify-between mb-3">
          <p className="text-white/40 uppercase tracking-widest text-xs">AI Study Plan</p>
          <span className="text-[10px] uppercase tracking-wider px-2 py-0.5 rounded-full bg-[#e8d5a3]/10 border border-[#e8d5a3]/20 text-[#e8d5a3]/60">
            Phase 4
          </span>
        </div>

        <p className="text-white/60 text-sm mb-4 leading-relaxed">
          {targetExam
            ? `Your personalised ${targetExam} study plan will be generated by AI based on your profile, timeline, and daily hours.`
            : "A personalised AI study plan will appear here once you've set your target exam."}
        </p>

        {/* Mock week preview */}
        <div className="flex flex-col gap-2 mb-4 opacity-40 pointer-events-none select-none">
          {["Week 1 — Quantitative Aptitude", "Week 2 — Reasoning", "Week 3 — General Awareness"].map((w, i) => (
            <div
              key={i}
              className="flex items-center gap-2 text-xs text-white/50"
            >
              <div className="w-1.5 h-1.5 rounded-full bg-[#e8d5a3]/40 shrink-0" />
              {w}
            </div>
          ))}
          <div className="text-xs text-white/20 pl-3.5">+ more weeks…</div>
        </div>

        <button
          disabled
          className="w-full py-2.5 rounded-xl bg-[#e8d5a3]/5 border border-[#e8d5a3]/10 text-[#e8d5a3]/30 text-sm cursor-not-allowed"
        >
          Generate my study plan
        </button>
      </div>
    </div>
  )
}